#!/usr/bin/env bash

# 根据系统创建相关目录
# 配置文件放置目录
dotfileDir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

if [[ ! -e ~/.antigen.zsh ]]; then
    curl -L git.io/antigen > ~/.antigen.zsh
fi

#######################################################################
#                          需要创建的文件目录                         #
#######################################################################

dires=(
    ${dotfileDir}/.vim/bundle/. # 创建插件安装文件夹
    ~/backup/.                  # 创建备份配置文件夹
)

for dir in ${dires[@]}; do
    if [[ ! -e ${dir%/*} ]]; then
        mkdir -p ${dir%/*}
    fi
    if [[ ${dir##*/} != . && ! -e ~/${dir} ]]; then
        ln -s ${dotfileDir}/${dir##*/} ~/${dir}
    fi
done

#######################################################################
#                   配置文件软链接到用户主目录当中去                  #
#######################################################################

# 引入 soft 中的dotfiles变量
dotfiles=(
    .eslintrc.js
    .gtags.conf        # 支持解析标签
    .vimrc             # vim 编辑器配置文件
    .vim               # vim 插件目录
    .ycm_extra_conf.py # c 语言语义补全配置文件
    .zshrc             # zsh 的配置文件
)

# 匹配的进行删除
# [#%] 尽可能短的从[左右]往[右左]删除字符
# (##|%%) 尽可能长的从[左右]往[右左]删除字符
# ${var([#%]|##|%%)pattern} * 万用符
# 如果配置文件在安装之前存在放入备份文件夹
for dotfile in ${dotfiles[@]}; do
    if [[ -L ~/${dotfile##*/} && -L ~/backup/${dotfile##*/} ]]; then
        echo "删除 ~/backup/${dotfile##*/} 文件"
        rm ~/backup/${dotfile##*/}
        echo "移动 ~/${dotfile##*/} 文件到 backup 文件夹"
        mv ~/${dotfile##*/} ~/backup
    elif [[ -L ~/${dotfile##*/} || -e ~/${dotfile##*/} && ! -L ~/backup/${dotfile##*/} ]]; then
        echo "移动 ~/${dotfile##*/} 文件到 backup 文件夹"
        mv ~/${dotfile##*/} ~/backup
    fi
    echo -e "软链接配置文件 ${dotfileDir}/${dotfile} 到 ~/${dotfile##*/}\n"
    ## 把配置文件软链接到用户主目录中
    ln -s ${dotfileDir}/${dotfile} ~/${dotfile##*/}
done

#######################################################################
#                          安装 vim 插件目录                          #
#######################################################################

if [[ `uname -s` =~ ^MSYS_NT || `uname -s` =~ ^MINGW64_NT ]]; then
    if [[ ! -e ~/vimfiles/autoload/plug.vim ]]; then
        curl -fLo ~/vimfiles/autoload/plug.vim --create-dirs \
            https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    fi
elif [[ `uname -s` == 'Darwin' ]]; then
    if [[ ! -e ~/.vim/autoload/plug.vim ]]; then
        curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
            https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    fi
elif [[ `uname -s` == 'Linux' ]]; then
    if [[ ! -e ~/.vim/autoload/plug.vim ]]; then
        curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
            https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    fi
else
    :
fi
